---
title: "Day 2 EOD Tasks"
author: "Jordan"
format: html
editor: visual
---

```{r}
#Section 2 
library(tidyverse)
#install.packages("palmerpenguins")
library(palmerpenguins)
library(tidyverse)

```


```{r}
#Finding derivatives 
eq1<- function(x) {
  x^2 
}

# First expression 
deriv_1<- D(expr = expression(x^2), name = "x")
deriv_1

x <- 3

eval(deriv_1)
# answer = 6 

# Second expression 
deriv_2<- D(expr = expression(2*(3 * a + 2)^4 - 5), name = "a")
deriv_2

a <- 1.2

eval(deriv_2)
# answer = 4214.78
```

```{r}
#Section 3 
data(package = 'palmerpenguins')
penguins <- penguins

#create a ggplot of bill length versus bill depth 
ggplot(data = penguins, aes(x= bill_length_mm, y=bill_depth_mm))+
  geom_point(aes(color = species))+
  scale_color_manual(values = c("dodgerblue", "darkorange2", "deeppink"))+
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       title = "Palmer penguins bill size measurements")
```

```{r}
# jitter plot of flipper length by species 

ggplot(data = penguins, aes(x = species, y = flipper_length_mm))+
  geom_jitter(aes(color = species))+
  scale_color_manual(values = c("dodgerblue", "darkorange2", "deeppink"))+
  labs(x = "Species",
       y = "Flipper Length (mm)",
       title = "Palmer penguins flipper measurements")

```


